### ISSUE TITLE
Win32-speed up EnumSerialPorts

### ISSUE THREAD

**Issue by dotnfc** [NordicSemiconductor/pc-ble-driver#123]
how about to change the WMI query string to reduce enum time:
_{pc-ble-driver}\src\common\platform\win\serial_port_enum.cpp | EnumSerialPorts()_

from:
`dhGetValue(L"%o", &colDevices, wmiSvc, L".ExecQuery(%S)", L"Select * from Win32_PnPEntity");`
to
`dhGetValue(L"%o", &colDevices, wmiSvc, L".ExecQuery(%S)", L"Select * from Win32_PnPEntity WHERE Name LIKE '%COM%'");`

in my test, this will reduce time from ~500ms to ~250ms.

**Comment by kenr** [comment]
Hi @dotnfc, thank you for this info, will try to include this in the next release.
