### ISSUE TITLE
[This is not an issue] What does "adapter_t" mean? 

### ISSUE THREAD

**Issue by HeXiang708** [NordicSemiconductor/pc-ble-driver#14]
Hello guys,

I find a new parameter "adapter_t" in every function, I want to know what that mean?

Thanks in advance for your help.

Xiang

**Comment by CoqRogue** [comment]
One of the things with the updated api for the connectivity project is that we wanted multiadaptr support. `adapter_t` gives us that. When you call `sd_rpc_adapter_create`, found in `sd_rpc.h`, you get an `adapter_t` returned. Sending this in to all the other functions will allow you to differentiate between the adapters you are connected with. Our [javascript bindings](https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/src/driver.cpp#L649) may give you an idea on how to use it.

**Comment by HeXiang708** [comment]
Thank you! Your javascript bindings help me so much.
