### ISSUE TITLE
pc-ble-driver running on iMX6 UL-2 S evk and using /dev/ttymxc2 as UART device

### ISSUE THREAD

**Issue by frvieren** [NordicSemiconductor/pc-ble-driver#143]
Hallo,

Just wondering, in the documentation it is mentioned that any architecture is supported that runs for example Linux, thus also it should work on a iMX6 UL board? Currently I'm doing a setup between a iMX6 UL-2 S Exceet evk and a Nordic nRF52 DK, the idea is to run a serialized application (e.g. the HR applic) on the iMX6 board and running the Nordic HR connectivity applic on the Nordic board. Transport link between the 2 boards is UART.

It seems a  tough job to replace the nrf_drv_uart.c driver by one that supports the iMX6 board that fits the serialize concept. 

Thanks,
Best regards,
Frank

Update 29/09/2018:
--------------------------
Finally got the Nordic example HR monitor application ported to iMX6 Exceet evk board. 
Next step setting up the physical connection between both boards. Feeling excited! 

Update 03/10/2018:
-----------------------
See my comments for this reported issue:
https://github.com/NordicSemiconductor/pc-ble-driver/issues/135

**Comment by frvieren** [comment]
Hi,

The nRF52 DK operating as connectivity board does not respond when the LINK CTRL packet is sent from the iMX6 exceet board. After 6 try-outs the application exists. The BLE driver is not initialized.
![image](https://user-images.githubusercontent.com/43606039/46426734-b8143800-c73f-11e8-9532-897542468113.png)

**Comment by frvieren** [comment]
See further progress of this setup/use case in the Nordic Dev zone:

https://devzone.nordicsemi.com/f/nordic-q-a/39173/no-valid-bidirectional-uart-communication-between-the-imx6-ul-s-evk-board-running-the-nordic-ble-driver-from-git-and-the-nrf52-dk-pca10040-when-running-the-nordic-hr-connectivity-software?ReplySortBy=CreatedDate&ReplySortOrder=Descending

**Comment by bihanssen** [comment]
Hi, @frvieren. I'm gonna close this issue here in favor of the DevZone ticket to avoid duplicated follow up. Feel free to re-open. Thanks.
