### ISSUE TITLE
pc-ble-driver-4.0.0 pre-built packages are missing header files.

### ISSUE THREAD

**Issue by greg4iiii** [NordicSemiconductor/pc-ble-driver#186]
- missing nrf_svc.h
- missing definition for adapter_t
Maybe we're supposed to use it in conjunction with a soft-device include folder, however, that's not expressed anywhere in the documentation.

**Comment by kenr** [comment]
Release 4.1.0 will contain the missing files. pc-ble-driver will also be available as a cmake module.
In addition we will add it to [vcpkg](https://github.com/Microsoft/vcpkg) to make it easier to start using.
