### ISSUE TITLE
[PC-BLE-Driver (C/C++)] Building Issue in "Compiling Connectivity HEX Files on Windows 10"

### ISSUE THREAD

**Issue by kwonjoon** [NordicSemiconductor/pc-ble-driver#202]
I am trying to install pc-ble-driver (c/c++) according to installation guide in this Git Hub.
However, in the "3. MSBuild" stage of the "Compiling Connectivity HEX Files on Windows",
build error which is related to "connectivity_1.0.0_usb_with_s132_3.1.0" occur as following.

![image](https://user-images.githubusercontent.com/47745520/52952687-b5ea0780-33c8-11e9-9360-a00cb61d8611.png)
![image](https://user-images.githubusercontent.com/47745520/52952742-df0a9800-33c8-11e9-8b3e-d4e9e4f69fd2.png)

Attached figures mention that compiler do not find "conn_ble_l2cap_sdu_pool.h" and "conn_ble_l2cap_sdu_pool.c" in the following path :

C:\Users\krbong\AppData\Local\Temp\pc-ble-driver\sdks\v15\nRF5_SDK_15.2.0_9412b96\
components\serialization\connectivity\codecs\ble\serializers

However, in that path, "conn_ble_l2cap_sdu_pool.h" and "conn_ble_l2cap_sdu_pool.c" are
exist as following figure (added "conn_ble_l2cap_sdu_pool_1.h" and "conn_ble_l2cap_sdu_pool_1.c"
for personal test)

![image](https://user-images.githubusercontent.com/47745520/52953125-e7af9e00-33c9-11e9-81e8-5032c07c7b80.png)

Also, I checked makefile in the following path with notepad :
C:\Users\krbong\AppData\Local\Temp\pc-ble-driver\sdks\v15\nRF5_SDK_15.2.0_9412b96\
examples\connectivity\ble_connectivity\pca10056\ser_s132v3_usb_hci\armgcc

![image](https://user-images.githubusercontent.com/47745520/52953303-6efd1180-33ca-11e9-937a-09adc6640536.png)
![image](https://user-images.githubusercontent.com/47745520/52953313-77554c80-33ca-11e9-908b-1cb0ac0d63a6.png)

The attached makefile figures show that there is no path error for 
"conn_ble_l2cap_sdu_pool.h" and "conn_ble_l2cap_sdu_pool.c" 
(changed from "conn_ble_l2cap_sdu_pool_1.c" to "conn_ble_l2cap_sdu_pool_1.c" for personal test)

I also tested another PC having windows 10 64 bit OS, and I faced same issue.
I think that this issue should be solved and guided for other beginners.

If you give some comments, it will be huge help for me.

Best regards,
Kwonjoon Lee

**Comment by kenr** [comment]
https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/Issues.md#long-paths-issue
