### ISSUE TITLE
Can't build connectivity using pc-ble-driver/master

### ISSUE THREAD

**Issue by jporcher** [NordicSemiconductor/pc-ble-driver#205]
choco install -y gcc-arm-embedded installs gcc-arm-embedded v7.2.1.20170904

However, when you later try to run from the hex folder:
cmake -G "Visual Studio 14" -DCOMPILE_CONNECTIVITY=1 -DCONNECTIVITY_VERSION=0.0.0

After nRF5_SDK_11.0.0_89a8197.zip is downloaded, you get an error reporting:
armgcc toolchain version is too old.  Needs to be 7.3.1 or newer.

**Comment by jporcher** [comment]
Is there any workaround? Should an older SDK be used?

**Comment by kenr** [comment]
Specific version of gcc-arm toolchain is updated in README.md (master). Latest version has issues.
