### ISSUE TITLE
Could connectivity hex files be packaged with releases?

### ISSUE THREAD

**Issue by jporcher** [NordicSemiconductor/pc-ble-driver#206]
I'm really having a hard time compiling connectivity hex files for pc-ble-driver 4.0.0. It would be very nice if those binaries could be part of the zips available at https://github.com/NordicSemiconductor/pc-ble-driver/releases.

**Comment by kenr** [comment]
They will be part of the release artifact in release 4.1.0.

**Comment by jpo38** [comment]
By the way, I see they are in the hex folder on the release tag. That's probably good enough...

Also, having debug binaries (with pdb file) could be nice if one wants to break in the code.
