### ISSUE TITLE
Failed to enable BLE stack when turn on the ATT_MTU config

### ISSUE THREAD

**Issue by rick1082** [NordicSemiconductor/pc-ble-driver#21]
Hello

I tried to run the heart_rate_collector example with "connectivity_1.0.1_115k2_with_s132_3.0.hex".
But the program crashed when doing the "sd_ble_enable()".
The error code is 0x04 which indicates that the memory assigned to Softdevice is not enough. 
Without enabled the “ATT MTU config”, the example project can run correctly.

Thanks for your attention.

**Comment by carlescufi** [comment]
What IC are you using, nRF51 or nRF52?

**Comment by rick1082** [comment]
I'm using nRF52(nRF52-DK, PCA10040), thank you :)

**Comment by bihanssen** [comment]
@rick1082 The values in the example were not valid due to insufficient memory. I have amended the example with new values so it should be ok now.

**Comment by rick1082** [comment]
Thank you @bihanssen, seems the issue can be closed. There's no error when enabled the ATT_MTU config.
