### ISSUE TITLE
Please make LED flash green for nRF52840-PCA10059

### ISSUE THREAD

**Issue by jporcher** [NordicSemiconductor/pc-ble-driver#221]
nRF51 dongle (SD API v2) had green LED on when plugged.

I'm using nRF52840-PCA10059 with connectivity_4.0.0_usb_with_s140_6.1.0 and it has no LED at all when plugged.

As the dongle has no packaging (and so is not keyed), you may plug it incorrectly to the USb port (upside down) the green flash was helping to detect that. Without any LED on, it's hard to say if the dongle is plugged correctly.

**Comment by bihanssen** [comment]
Thanks for the input, you state a valid point. We have added the request to our backlog. Closing this issue.

**Comment by jporcher** [comment]
Thanks!
