### ISSUE TITLE
¿Is posible develop a java native interface for pc-ble-driver?

### ISSUE THREAD

**Issue by gustavo84** [NordicSemiconductor/pc-ble-driver#24]
It is possible to connect this driver to java via jni. This way there would be support for java for desktop and for windows, linux and mac. I think it is important to develop this wrapper

**Comment by bihanssen** [comment]
I believe it should be fully possible to create bindings to Java via jni. We at Nordic, however, do not currently have any plans to add Java bindings. Though if someone outside Nordic would like do so it should be fully possible.

**Comment by bihanssen** [comment]
Closing this issue now, please reopen if further questions.
