### ISSUE TITLE
Apply the patch from the unzipped SDK folder

### ISSUE THREAD

**Issue by gokhangocmen94** [NordicSemiconductor/pc-ble-driver#35]
In Chapter: Compiling the connectivity .hex files

2.Apply the patch hex/sd_api_v<x>/SDK<ver>_connectivity.patch from the unzipped SDK folder (e.g. git apply -p1 --ignore-whitespace /repos/pc-ble-driver/hex/sd_api_v2/sdk110_connectivity.patch)

How Can I apply the patch on Windows?

Thanks for helping.

**Comment by bihanssen** [comment]
Hi,
to run it on Windows you will need git bash terminal or similar bash terminal.
Either run the [bash script](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/hex/bootstrap.sh#L110) directly, or copy the [patch command](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/hex/bootstrap.sh#L110), replace the variables, and run it from the terminal.
