### ISSUE TITLE
Any plan to release the pc-ble-driver for SDK13?

### ISSUE THREAD

**Issue by Arepas** [NordicSemiconductor/pc-ble-driver#42]
Hi guys any plan for release a compatible pc-ble-drver for SDK13 ble_connectivty firmware?

Regards

**Comment by bencefr** [comment]
Hi @Arepas, I would think we will provide such driver however anyone who could give you the correct answer is currently unavailable. I'll follow up.

**Comment by bencefr** [comment]
@Arepas , the answer is yes, we definitely do plan to support latest SDK, however currently we are a bit under-powered and also have other priorities to focus on. Development will pick up much more momentum after the summer vacations are over.

**Comment by bartholmberg** [comment]
Any updates on the new driver for SDK 13?

**Comment by bihanssen** [comment]
@bartholmberg @Arepas Work for adding support for latest relevant SDK has been planned in and will start shortly. Expect it to take around a month give or take, depending on other activities.
