### ISSUE TITLE
Support on DFU

### ISSUE THREAD

**Issue by westside** [NordicSemiconductor/pc-ble-driver#43]
* Is this library support DFU?

**Comment by bencefr** [comment]
No, this layer doesn't. DFU support is implemented in

- [pc-ble-driver-js](https://github.com/NordicSemiconductor/pc-ble-driver-js) 
- [pc-nrfutil](https://github.com/NordicSemiconductor/pc-nrfutil)

Note: pc-nrfutil is based on [pc-ble-driver-py](https://github.com/NordicSemiconductor/pc-ble-driver-py) which itself doesn't support DFU.
