### ISSUE TITLE
The timeout happened when running on MTK MT7688 platform

### ISSUE THREAD

**Issue by rick1082** [NordicSemiconductor/pc-ble-driver#44]
Hello :)

There is a case that I want to running the pc-ble-driver on MediaTek [MT7688 ](https://labs.mediatek.com/en/platform/linkit-smart-7688#HDK)platform.  
The MT7688 is using MIPS CPU architecure, and I programmed the module with [Widora](https://github.com/widora/openwrt_widora), a modified OpenWRT OS on it.
I have cross-compiled the pc-ble-driver to run on the MT7688 module, and possible to use USB to serial bridge to connect the connectivity device (nRF52) and run the example.
But I found that when connected the nRF52 chip to the MT7688 directly. The pc-ble-driver failed to open the communication in very high failed rate with error code 0x0D (timeout), it is very hard to success (near 1/20).
Since  there's no flow control pin (RTS and CTS) on MT7688 module, I have tried to disable the flow control in connectivity firmware by modified _components/serialization/common/ser_config.h_
`#define SER_PHY_UART_FLOW_CTRL      APP_UART_FLOW_CONTROL_DISABLED
`
and also enlarge the "OPEN_WAIT_TIMEOUT" in [here](https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/src/common/transport/h5_transport.cpp#L75), but no help.
I also tried to execute the test_uart in the pc-ble-driver repository, and no abnormal found.

Is there any parameter I can modify to solve this issue ?
Thanks for your attention.

**Comment by bihanssen** [comment]
Hi @rick1082. 
The UART flow control is important to avoid buffer overruns. If you simply disable flow control it will likely fail, especially at high baud rates. If you are not able to support flow control, the only option I see would be to lower the baud rate sufficiently.
