### ISSUE TITLE
Calling sec_params_reply() from sec_params_request event handler crashes program

### ISSUE THREAD

**Issue by ThomasGerstenberg** [NordicSemiconductor/pc-ble-driver#45]
Creating issue based on the DevZone question here:
https://devzone.nordicsemi.com/question/110137/pc-ble-driver-10-bonding/?answer=165741#post-id-165741

I have confirmed the crashing behavior using the python bindings (v0.10.0), and also confirmed that calling `sec_params_reply()` from the main context does not crash the program

**Comment by bihanssen** [comment]
Thanks for reporting.

**Comment by bihanssen** [comment]
Closing this issue. Please report on devzone if this is still an issue in the latest version of pc-ble-driver.
