### ISSUE TITLE
API to reset attached nRF device

### ISSUE THREAD

**Issue by torfinnberset** [NordicSemiconductor/pc-ble-driver#48]
Currently, when I close my application that uses pc-ble-driver, the device continues to advertise / being connected to a peer. I want to reset the device (currently the nRF51 dongle) when I exit my program. I tried using `sd_rpc_close`, but this only closes the UART connection, and leaves the device still operational.

I found an unimplemented API called `conn_systemreset` in ble_impl.cpp (https://github.com/NordicSemiconductor/pc-ble-driver/blob/4bda53f1ad73b0ba55e02842052e1843c69aea1f/src/common/ble_impl.cpp#L248), which I assume was meant for this purpose. The only other option I found was to try to stop advertising / gap_disconnect just before exiting the program, but I'm not confident that will always work.

**Comment by bihanssen** [comment]
Hi @torfinnberset,
it is correct that the conn_systemreset is meant for the purpose of resetting the connectivity device. The reset mechanism is being used internally in pc-ble-driver transport layer, but it hasn't been exposed up to the end user API . I agree it would be convenient to have it accessible, will add it to the backlog.

The only way to trigger reset currently would be to call close, and the open again, as the reset is triggered as part of the transport initialization.
