### ISSUE TITLE
nRF dongle overheating during prolonged use when using connectivity firmware

### ISSUE THREAD

**Issue by torfinnberset** [NordicSemiconductor/pc-ble-driver#49]
We are using the nRF51 dongle in a production test environment, but we are having issues with the dongle overheating during prolonged use. When overheated, we start to see failures in connecting to and using the device. Letting it cool down a bit seems to get us back on track.

Is there any room for power optimization in the connectivity firmware?

**Comment by bihanssen** [comment]
Hi,
if there is an issue with overheating, I suspect it could be the onboard JLink debugger chip that is overheating. It tends to get hot, though I haven't heard of failures until now. If it is the JLink device that gets hot then it would not help adding power optimization to the connectivity firmware. 
Please try posting on DevZone, the support team might have suggestions to this hardware related issue.
