### ISSUE TITLE
C and C++ mixup

### ISSUE THREAD

**Issue by emidttun** [NordicSemiconductor/pc-ble-driver#5]
The files ```app_*_pc.c``` have an extension suggestion it is a C file. But includes the C++ keywords ````new``` and ```delete```. If this really works it is probably by accident. It should be changed to _either_ C or C++.

**Comment by CoqRogue** [comment]
It does work. And not by accident. As most (all?) major c/c++ compilers use the same compiler for both languages and as none of them differenciate between languages based on file extension, mixing of the languages is not a practical issue. 

Designwise the separation makes sense. All files with a .c extension only expose a c api externally, and only utilize some c++ features as they are meant as a bridge between a c interface and c++ classes doing the grunt work.

And in the end, even the c code is compiled as c++, so it is not an issue at all. It is just clarifying the api exposed.
