### ISSUE TITLE
Hi guys i met errors while set up on my device.

### ISSUE THREAD

**Issue by KwonGiho** [NordicSemiconductor/pc-ble-driver#54]
Hi genius guys.
I’m a junior developer who is making DFU software for windows 10. I encountered new errors while setting up the following Installation.md

Attached below are the photos and explanation on how I approached to build this repository. 
The first error was encountered while using cmake. 
![image](https://user-images.githubusercontent.com/14024193/32035594-5f289c38-ba55-11e7-9991-2f3f44024174.png)
I followed the steps of [windows-2] (https://github.com/NordicSemiconductor/pc-ble-driver/blob/master/Installation.md#windows-2)

My device environment is Windows 10 x64bit, using Visual Studio 15 2017. It was a success when I build it without “Win64” keyword but there was a new warning/error message about “Architecture not set, using native…”  
I would like to know what does that warning message mean and what could be done to solve it? 
Anyway, I have proceeded with the next step while ignoring the previous warning message by typing msbuild ALL_BUILD.vcxproj /p:Configuration=Debug
![image](https://user-images.githubusercontent.com/14024193/32035838-ac799c34-ba56-11e7-9da8-8f6eb63458ab.png)
And Error 3 appeared. I was thinking if this Error 3 was the result of Error 1? Could you please recommend or suggest what can I do to build this repository? 
Thank you.

**Comment by bihanssen** [comment]
Hi @KwonGiho 
It is important to have Boost compiled correctly in the same architecture as you compile pc-ble-driver in. Your first error seems to indicate you have run cmake before with a different setting. You should delete all files in the build folder and run cmake again.
The second error window might indicate mismatch in architecture of compiled Boost and pc-ble-driver.

You can't mix 64 bit Boost and 32 bit pc-ble-driver, so make sure they are the same. I suggest rebuilding both in 32 bit.

**Comment by KwonGiho** [comment]
I’m already set up all of them.

But still not operating yet too T^T

By the way , I solve it on MacOS but there is has an issue on MacOS.

I think this library require J-Link Device to connect each other right? ( I think that Windows need J-Link too , right? )

I can’t connect both of device without J-Link device?

Thanks for reading.

**Comment by bihanssen** [comment]
Hi,
pc-ble-driver requires an nRF development kit or dongle with JLink debugger. 

When you say *both* devices, what devices do you mean? The peer device (the remote device connected to over BLE) can be any BLE device, no requirement for JLink there.

**Comment by bencefr** [comment]
Should this issue be still relevant, feel free to reopen it.
Ask questions on [DevZone](https://devzone.nordicsemi.com/)
