### ISSUE TITLE
Suggested improvements in the Python API and examples

### ISSUE THREAD

**Issue by emidttun** [NordicSemiconductor/pc-ble-driver#6]
Here are some snippets from the heart_rate_collector example:
```python
def ble_evt_handler(ble_event):
    try:
        if ble_event is None:
            print "Received empty ble_event"
            return
       # Functions continues

# Later in the file
def main(serial_port):
    ble_driver.sd_rpc_evt_handler_set(ble_evt_handler)
``` 

It would be a good improvement if:
* The function signature for ```ble_evt_handler``` was documented in the ```sd_rpc_evt_handler_set()``` documentation. Now the best clue is the example, but is it _the_ way to do it, or just an example?
* The try/except block is rather large, and it is unclear what could cause an exception. For this file there seems to be nothing, unless it should catch exception that propagated from other function calls.
* The testing if ```ble_event``` is ```None``` seems unnecessary given that the function is a callback. If nothing is received then the function shouldn't be called. Also it fails to protect against the case where a valid object is received, but it is not a valid ```ble_event```.

**Comment by carlescufi** [comment]
This has been overhauled now, so it doesn't apply anymore.
