### ISSUE TITLE
Can't generate Python bindings with Python 2.7.10

### ISSUE THREAD

**Issue by bihanssen** [NordicSemiconductor/pc-ble-driver#7]
Generating Python bindings of pc-ble-driver fails when using Python version 2.7.10. Downgrading to version 2.7.6 works as expected.

**Comment by carlescufi** [comment]
closing after repo overhaul. Reopen if it's still an issue.

**Comment by carlescufi** [comment]
closing after repo overhaul. Reopen if it's still an issue.
