### ISSUE TITLE
nRF51 Bluetooth Smart GATT/GAP Driver for Linux issue

### ISSUE THREAD

**Issue by cloud740424** [NordicSemiconductor/pc-ble-driver#8]
Hi,
I am a newbie to Nordic BLE.
I can build the heart_rate_collector example code on my cross compile environment (Linux SWRD 2.6.32.26-175.fc12.i686). 

But I encountered great difficulties in executing the example code, would you please help me on this.

The error messages: 
![2015-11-12_162303](https://cloud.githubusercontent.com/assets/15648806/11116596/9abd8b24-896e-11e5-8266-761bd18deeed.png)

The error code appears in sd_ble_version_get(&version) function as follows:
![2015-11-12_162928](https://cloud.githubusercontent.com/assets/15648806/11116621/c32891bc-896e-11e5-80b1-b52e24f21bb9.png)

**Comment by carlescufi** [comment]
closing after repo overhaul. Reopen if it's still an issue.
