### ISSUE TITLE
build warnings if I build branch v6-upgrade for x64 targets.

### ISSUE THREAD

**Issue by zyan-wu** [NordicSemiconductor/pc-ble-driver#91]
sd_api_v6/sdk/components/libraries/util/app_util.h:1193:10: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     if (((uint32_t)ptr >= (uint32_t)STACK_BASE) &&

sd_api_v6/sdk/components/serialization/common/struct_ser/ble/ble_struct_serialization.c:474:23: warning: cast from pointer to integer of different size [-Wpointer-to-int-cast]
     uint32_t buf_id = (uint32_t)p_struct->p_data;

**Comment by bihanssen** [comment]
Thanks for reporting.

**Comment by kenr** [comment]
Fixed in: https://github.com/NordicSemiconductor/pc-ble-driver/pull/163
