### ISSUE TITLE
v6-upgrade has issues with sd_ble_gap_scan_start & sd_ble_gap_scan_stop.

### ISSUE THREAD

**Issue by zyan-wu** [NordicSemiconductor/pc-ble-driver#95]
Here is the problem.

I invoke scan_start & then invoke scan_stop before any adv_report event come back. Afterwards, I cannot invoke scan_start any more.

I've done some debugging myself. Here is the reason.
In app_ble_gap_sec_keys.cpp: app_ble_gap_scan_data_set() the data is not fetched by any adv so we cannot set the new p_data; which causes the error.

I am thinking of clear the scan_data when stop successfully. However, there could be case that I am invoking scan_stop while adv_report is coming at the same time so you probably need some way to protect this static buffer.

**Comment by bihanssen** [comment]
This was a bug with the old version of connectivity. Should be fixed from version 4.0 of pc-ble-driver.
